version: '3.4'

services:
  maryshoppinswebmvc:
    image: ${DOCKER_REGISTRY-}maryshoppinswebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  maryshoppinspublicapi:
    image: ${DOCKER_REGISTRY-}maryshoppins
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile

